package com.ibm.btt.application.op;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.types.impl.Currency;

/**
 * Class Generated by BTT Tool Created since: 2012/09/27 11:17:22
 */
public class InitPaginationData extends BTTServerOperation
{
	private Random rand = new Random();

	@Override
	public void execute() throws Exception
	{
		// TODO Auto-generated method stub

		KeyedCollection opData = this.getContext().getKeyedCollection();
		IndexedCollection allAccountList = (IndexedCollection) opData.getElementAt("AllAccountList");
		IndexedCollection accountInfoList = (IndexedCollection) opData.getElementAt("AccountInfoList");
		System.out.println("==============InitPaginationData start====================");

		// set value
		for (int i = 0; i < allAccountList.size(); i++)
		{
			allAccountList.setValueAt(i + ".d1", "d1" + i);
			allAccountList.setValueAt(i + ".d2", "d2" + i);
			allAccountList.setValueAt(i + ".d3", "d3" + i);
			
		}

		

		AccountListDB.init(allAccountList);
		
		//set the first data
		AccountListDB.getAllAccountList(1, accountInfoList);
		
		opData.setValueAt("TotalNum", allAccountList.size());
		System.out.println("==============InitPaginationData end====================");

		fireExitEvent("ok");
	}
}
