package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;


import com.ibm.btt.base.Context;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2014/01/06 17:58:49
 */
public class Multiselect_B_31 extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context =this.getContext();
	  for(int i=0;i<10;i++){
		  context.setValueAt("Multiselect_B_31List."+i+".Multiselect_B_31Data", i*i);
		  context.setValueAt("Multiselect_B_31List."+i+".Multiselect_B_31Data01", "beijing"+i);
	  }
	  this.fireExitEvent("opEvt");
  }
}
